require 'yaml'

creds = YAML.load_file('variables.yml')

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.hostname = "M11-EAC4-debian12"

  config.vm.network "private_network", ip: "192.168.11.104"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL

    apt update
    apt upgrade -y

    apt install -y \
      ca-certificates \
      curl \
      gnupg

    install -m 0755 -d /etc/apt/keyrings

    curl -fsSL https://download.docker.com/linux/debian/gpg \
      -o /etc/apt/keyrings/docker.asc

    chmod a+r /etc/apt/keyrings/docker.asc

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
      https://download.docker.com/linux/debian \
      bookworm stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt update

    apt install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io \
      docker-buildx-plugin \
      docker-compose-plugin

    useradd -m -s /bin/bash -G sudo,docker #{creds['username']}

    echo "#{creds['username']}:#{creds['password']}" | chpasswd

    echo "#{creds['username']} ALL=(ALL) NOPASSWD:ALL" \
      > /etc/sudoers.d/#{creds['username']}

  SHELL
end
