Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end
  config.vm.network "private_network", ip: "192.168.11.200"
  config.vm.hostname = "microk8s-pedragosa"
  config.vm.box_check_update = false
end
